# Generated by Django 3.1.1 on 2021-01-03 02:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_application_rsvp"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="phone_number",),
        migrations.RemoveField(model_name="application", name="q1",),
        migrations.RemoveField(model_name="application", name="q2",),
        migrations.RemoveField(model_name="application", name="q3",),
        migrations.AddField(
            model_name="application",
            name="eligibility_agree",
            field=models.BooleanField(
                default=True,
                help_text="I confirm that I will be over 18 years old and a university student on February 6, 2021.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="resume_sharing",
            field=models.BooleanField(
                default=False,
                help_text="I consent to IEEE UofT sharing my resume with event sponsors (optional).",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="birthday",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2003, 2, 6),
                        message="You must be over 18 years old on February 6, 2021 to participate in MakeUofT.",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="conduct_agree",
            field=models.BooleanField(
                help_text='I have read and agree to the <a href="https://docs.google.com/document/d/1RH36R1nt8KQfKtd2YoNAJNuaCW5um55a6oVP_bWRK6U/edit" target="_blank">code of conduct</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="school",
            field=models.CharField(help_text="University", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("undergraduate", "Undergraduate"),
                    ("gradschool", "Graduate School"),
                ],
                max_length=50,
            ),
        ),
    ]
